[package]
name = "pig-latin-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-vowel = "0.1.0"
log = "0.4.22"
log4rs = "1.3.0"
