[workspace]

members = [
    "branches",
    "converter",
    "fibonacci",
    "functions",
    "guessing_game",
    "hello_cargo",
    # "hello_world", // This is not a Cargo crate
    "loops",
    "ownership",
    "references-and-borrowing",
    "twelve-days-of-christmas",
    "variables",
]

resolver = "1"
